# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c033070715191a6ae4d3b24fbf9e83eb59bcb8c32165f6adb9cd80cbcd2891df1095aeb246a862755b1c156e01d607c4d224bb35d9a099a2bbd52110adfe227

test:
  secret_key_base: ee1b7d107a9e1005a9bde0257432fd4900eb9eca26d850c03c7a21b6b2a0033136125eec44e8588fad671c5c69104f4a9b0f0369889470897d3327929f37f8d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
